# Generated by Django 3.2.8 on 2021-12-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Body_Temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('Symptom1', models.CharField(blank=True, max_length=50, null=True)),
                ('Symptom2', models.CharField(blank=True, max_length=50, null=True)),
                ('Symptom3', models.CharField(blank=True, max_length=50, null=True)),
                ('Symptom4', models.CharField(blank=True, max_length=50, null=True)),
                ('Symptom5', models.CharField(blank=True, max_length=50, null=True)),
                ('Symptom6', models.CharField(blank=True, max_length=50, null=True)),
                ('Symptom7', models.CharField(blank=True, max_length=50, null=True)),
                ('Symptom8', models.CharField(blank=True, max_length=50, null=True)),
                ('Symptom9', models.CharField(blank=True, max_length=50, null=True)),
                ('Medical_History1', models.CharField(blank=True, max_length=50, null=True)),
                ('Medical_History2', models.CharField(blank=True, max_length=50, null=True)),
                ('Medical_History3', models.CharField(blank=True, max_length=50, null=True)),
                ('Medical_History4', models.CharField(blank=True, max_length=50, null=True)),
                ('Medical_History5', models.CharField(blank=True, max_length=50, null=True)),
                ('Medical_History6', models.CharField(blank=True, max_length=50, null=True)),
                ('Other_Medical_History', models.TextField()),
                ('Vaccinated', models.CharField(blank=True, max_length=50, null=True)),
                ('Vaccine_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Additional_Info', models.TextField()),
            ],
        ),
    ]
