# Generated by Django 3.2.8 on 2021-12-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessment_body_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='Symptom1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='Symptom2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='Symptom3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='Symptom4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='Symptom5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='Symptom6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='Symptom7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='Symptom8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='Symptom9',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
